import { initHeaderOnScroll, initNav, initToTop } from "./nav.js";
import { initFaq } from "./faq.js";
import { initTheme } from "./theme.js";
import { initPricing } from "./pricing.js";
import { initReveal } from "./reveal.js";
import { initSlider } from "./slider.js";
import { initCopyCode } from "./copy.js";
import { initRecords } from "./records.js";
import { initContactForm } from "./contact-form.js";

initNav();
initHeaderOnScroll();
initToTop();
initTheme();
initFaq();
initPricing();
initReveal();
initSlider();
initCopyCode();
initRecords();
initContactForm();
